server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5333/product_catalog
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: product-catalog-service
  main:
    web-application-type: SERVLET

management:
  tracing:
    sampling:
      probability: 1.0