server:
  port: 8082

spring:
  application:
    name: user-authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5331/user_authentication
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect